### ISSUE TITLE
Local images do not show up in output on windows

### ISSUE THREAD

**Issue by olaruandreidan** [travs/markdown-pdf#109]
Though the image is being seen in the preview, even when trying to insert the image both with a relative and an absolute path it did not show up in the output.

**Comment by dalzzing2** [comment]
me either.

**Comment by ChristopherMeek** [comment]
Same here.

**Comment by mbilbille** [comment]
+1 same here (it was working on previous versions)

**Comment by irenemeanspeace** [comment]
+1 :(

**Comment by DoorCrasher** [comment]
+1 !

**Comment by shark-oxi** [comment]
The alt attribute is shown instead of the picture (for local picture).

**Comment by robkrause** [comment]
+1

**Comment by Hotwill** [comment]
+1

**Comment by spaelling** [comment]
+1

**Comment by spaelling** [comment]
fixed it and created a [pull request](https://github.com/travs/markdown-pdf/pull/115)

**Comment by coolulu** [comment]
+1

**Comment by devilmagic** [comment]
modify `~/.atom/packages/markdown-pdf/lib/markdown-pdf.js`
search `function processSrc`
```javascript
function processSrc(src){
  //make a local img src path into a "file:///absolute/path/" if it isn't already
  if(url.parse(src).protocol){
    //if the src already starts with "file://", "https://", etc., it's already in the right form (URI)
    return src;
  }
  else if(path.resolve(src) !== src){
    //if path is not absolute and has no protocol, it should be relative, so make it a URI
    src = path.resolve(path.dirname(outPath), src);
    return 'file:///' + src;
  }
  else{
    //otherwise, the src is an absolute path. In this case we can just prepend "file://" to it
    return 'file:///' + src;
  }
}
```

After modifed

```javascript
function processSrc(src){
  //make a local img src path into a "file:///absolute/path/" if it isn't already
  if(url.parse(src).protocol){
    //if the src already starts with "file://", "https://", etc., it's already in the right form (URI)
    return 'file:///' + src;
  }
  else if(path.resolve(src) !== src){
    //if path is not absolute and has no protocol, it should be relative, so make it a URI
    src = path.resolve(path.dirname(outPath), src);
    return 'file:///' + src;
  }
  else{
    //otherwise, the src is an absolute path. In this case we can just prepend "file://" to it
    return 'file:///' + src;
  }
}
```

**Comment by hkinks** [comment]
+1

**Comment by kayler-renslow** [comment]
+1

**Comment by aleksandr-m** [comment]
Another pull request for the same #121

**Comment by jen-ren** [comment]
Installed current version and having this problem.

**Comment by mcm-jyl** [comment]
At least with relative path it doesn't work:

` ![](img/name.png)`

is properly displayed in the preview on Windows (having a subdirectory img containing name.png) but the generated PDF doesn't contain images.

Atom 1.13.0 with latest version.
Preview: Markdown Preview Plus

**Comment by noraj1337** [comment]
@mcm-jyl : 0 commit in 10 months, that will be a wontfix

**Comment by nateGeorge** [comment]
+1

**Comment by Erik1992** [comment]
+1

**Comment by travs** [comment]
I merged a PR that alleges to fix this, but since this is a popular issue and I don't have a windows right now, can someone update to `>=1.5.2` and see if this works now?
Thinking about doing a major rewrite of this whole package, shoot me an email if anyone here is interested in helping maintain.

**Comment by IreneCrisologo** [comment]
I upgraded to 1.5.4 and now it completely doesn't work :( It just generates a pdf file with whatever text is in my clipboard (the last thing I Ctrl+C).

**Comment by travs** [comment]
@IreneCrisologo 
I get this behaviour when I click the markdown-preview-plus pane before running `convert`.
Make sure the last thing you click on before running `convert` is the pane containing the markdown text, and try it again.
Let me know if the same thing still happens to you when you do that, or if it works correctly.

If this is the cause, I have an issue opened that would also clear this up #155

**Comment by IreneCrisologo** [comment]
@travs the same thing still happens, even when the last thing I click is the pane with the markdown text.
